### ISSUE TITLE
migrate to TypeScript

### ISSUE THREAD

**Issue by flexbox** [flexbox/inspiration#44]
As a developer
I can use Typescript
So that I am more confident with my code

- [ ] use `gatsby recipes` to migrate
https://davidl.fr/blog/migrate-gatsby-to-typescript

- [ ] or you can check this PR https://github.com/flexbox/artaufeminin/pull/14/files

--- 

## Adding typescript

- [x] Migrate `*.js` files to `*.tsx`
- [x] remove "prop-types": "^15.6.2", from `package.json`
- [x] add interface when necessary (you can have a look at [the typescript cheatsheet](https://github.com/typescript-cheatsheets/react))

more [reading on the documentation ](https://www.gatsbyjs.com/docs/how-to/custom-configuration/typescript/)

and feel free to create a new gatsby project with typescript to have a look

**Comment by MatthysDucrocq** [comment]
has been Migrated to typescript
