### ISSUE TITLE
Bump dependencies

### ISSUE THREAD

**Issue by flexbox** [flexbox/inspiration#45]
As a developer 
I can use the last version of the libs
So that I am not confused when I read the documentation

---

- [x] migrate to Gatsby3
- [x] run `yarn upgrade-interactive --latest`
- [x] try to upgrade green dependencies one step at a time
- [x] bump major version of gatsby https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/

⚠️ do not mix `npm` and `yarn` commands otherwise it will not work

**Comment by MatthysDucrocq** [comment]
Now migrated to gatsby 3
